spring:
  application:
    name: companies-crud
  datasource:
    url: jdbc:postgresql://localhost:5431/companies
    username: debuggeandoideas
    password: HFBWEFUWEBFWNOEF
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
